name: Auto Publish

on:
  schedule:
    - cron: '40 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout playwright-mcp
        uses: actions/checkout@v7
        with:
          repository: microsoft/playwright-mcp

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: '>=18'

      - name: Check and publish new versions
        uses: actions/github-script@v9
        with:
          script: |
            const fs = require('fs');
            const verfmt = /^v\.?(\d+\.\d+\.\d+)$/;
            const pkgname = 'patchright_mcp';

            let pkg = await (await fetch(`https://registry.npmjs.org/${pkgname}`)).json();
            let { stdout } = await exec.getExecOutput('git', ['tag']);
            console.log(stdout);
            for (let v of stdout.split('\n')) {
              let r = verfmt.exec(v);
              if (r != null) {
                r = r[1];
                await exec.exec('git', ['reset', '--hard', v]);
                let json = JSON.parse(fs.readFileSync('package.json'));
                json.name = pkgname;
                for (let [k, v] of Object.entries(json.dependencies)) {
                  if (k.startsWith('playwright'))
                    json.dependencies[k] = `npm:${k.replaceAll('playw', 'patch')}@${v.split('-')[0]}`;
                }
                console.log(JSON.stringify(json, null, '  '));
              }
            }
