name: Auto Publish

on:
  schedule:
    - cron: '40 8 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout playwright-mcp
        uses: actions/checkout@v7
        with:
          repository: microsoft/playwright-mcp
          fetch-tags: true

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: '>=18'

      - name: Check and publish new versions
        uses: actions/github-script@v9
        with:
          script: |
            const fs = require('fs');
            const verfmt = /^v\.?(\d+\.\d+\.\d+)$/;
            const pkgname = 'patchright-mcp-server';
            const reponame = 'scientificworld/patchright_mcp_actions';

            let banned = eval(await (await fetch(`https://raw.githubusercontent.com/${reponame}/main/banned-versions.js`)).text());
            let pkg = await (await fetch(`https://registry.npmjs.org/${pkgname}`)).json();
            let { stdout } = await exec.getExecOutput('git', ['--no-pager', 'tag']);
            for (let v of stdout.split('\n')) {
              let r = verfmt.exec(v);
              if (r != null) {
                r = r[1];
                if (r in pkg.versions || r in banned)
                  continue;
                await exec.exec('git', ['reset', '--hard', v]);
                let json = JSON.parse(fs.readFileSync('package.json'));
                json.name = pkgname;
                json.repository.url = `git+https://github.com/${reponame}.git`;
                if (!json.dependencies)
                  continue;
                for (let [k, v] of Object.entries(json.dependencies)) {
                  if (k.startsWith('playwright'))
                    json.dependencies[k] = `npm:${k.replaceAll('playw', 'patch')}@${v.replaceAll('^', '').split('-')[0]}`;
                }
                fs.writeFileSync('package.json', JSON.stringify(json, null, '  '));
                try {
                  await exec.exec('npm', ['install']);
                  await exec.exec('npm', ['run', 'npm-publish']);
                  await io.rmRF('node_modules');
                }
                catch {}
                break;
              }
            }
